# Generated by Django 5.2.8 on 2025-11-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_property_title_alter_property_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='ss', to='mysite.amenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='bath_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bed_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_property', to='mysite.city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='mysite.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='rules',
            field=models.CharField(choices=[('no_smoking', 'no_smoking'), ('pets_allowed', 'pets_allowed'), ('etc', 'etc')], max_length=50),
        ),
    ]
