# Generated by Django 5.2.8 on 2025-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_property_bathrooms_remove_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hosts', 'hosts'), ('guest', 'guest')], default='hosts', max_length=30),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
